### ISSUE TITLE
Migrirati proces kompajliranja Brotli modula sa DroneCI na GHA

### ISSUE THREAD

**Issue by igorhrcek** [mint-hosting/nginx-module-brotli#1]
Migrirati proces kompajliranja brotli nginx modula sa DroneCI na GitHub Actions i tom prilikom uvesti i podršku za Ubuntu 20.04.

**Comment by kozicpetar** [comment]
Nakon testiranja modula, process build-a je prebacen na github actions. Kod je komitovna i nalazi se u master branchu. Stari process da drone-CI je iskljucen.
