### ISSUE TITLE
 nginx 1.19.10

### ISSUE THREAD

**Issue by TheRealAstroboy** [mint-hosting/nginx-module-brotli#7]
Hello,

Nginx 1.19.10 and 1.20 are out...
Thanks for your work !

Astro

**Comment by igorhrcek** [comment]
Hi!

This repo is updated automatically, and we check for new versions every day. When nginx repo is updated with a new tag, the module is going to be compiled automatically.

From what I see they still haven't updated their repo, so we need to wait for that.
